"""A deterministic stand-in for a model provider."""

from __future__ import annotations

import json
from collections.abc import AsyncIterator

from core.models.types import (
    GenerateChunk,
    GenerateRequest,
    GenerateResponse,
    ToolCallRequest,
    ToolCallResponse,
    Usage,
)


class MockProvider:
    """Return stable text derived from the prompt."""

    async def generate(self, request: GenerateRequest) -> GenerateResponse:
        return GenerateResponse(
            text=mock_text(request.prompt),
            model=request.model,
            provider="mock",
            usage=Usage(input_tokens=len(request.prompt.split()), output_tokens=1),
            finish_reason="stop",
        )

    async def stream(self, request: GenerateRequest) -> AsyncIterator[GenerateChunk]:
        text = mock_text(request.prompt)
        for index in range(0, len(text), 24):
            yield GenerateChunk(text=text[index : index + 24], done=False)
        yield GenerateChunk(text="", done=True)

    async def tool_call(self, request: ToolCallRequest) -> ToolCallResponse:
        parsed = _explicit_call(request.prompt)
        if parsed is not None:
            name, arguments = parsed
            return ToolCallResponse(tool_name=name, arguments=arguments, text=None)
        generated = await self.generate(GenerateRequest(model=request.model, prompt=request.prompt))
        return ToolCallResponse(tool_name=None, arguments={}, text=generated.text)


def mock_text(prompt: str) -> str:
    """Build the mock provider's deterministic text."""

    lowered = prompt.lower()
    if "html" in lowered or "website" in lowered:
        return (
            "<!doctype html><html><head><title>OMNE</title></head>"
            "<body><p>Generated by the mock provider.</p></body></html>"
        )
    compact = " ".join(prompt.split())
    return f"mock-response:{compact[:240]}"


def _explicit_call(prompt: str) -> tuple[str, dict[str, object]] | None:
    marker = "CALL "
    if marker not in prompt:
        return None
    body = prompt.split(marker, 1)[1].strip()
    name, _, raw_args = body.partition(" ")
    if not name:
        return None
    if not raw_args:
        return name, {}
    loaded = json.loads(raw_args)
    if not isinstance(loaded, dict):
        return name, {}
    return name, loaded
