"""A deterministic stand-in for a model provider."""

from __future__ import annotations

import json
import re
from collections.abc import AsyncIterator

from core.models.types import (
    GenerateChunk,
    GenerateRequest,
    GenerateResponse,
    ToolCallRequest,
    ToolCallResponse,
    Usage,
)


class MockProvider:
    """Return stable text derived from the prompt."""

    async def generate(self, request: GenerateRequest) -> GenerateResponse:
        return GenerateResponse(
            text=mock_text(request.prompt),
            model=request.model,
            provider="mock",
            usage=Usage(input_tokens=len(request.prompt.split()), output_tokens=1),
            finish_reason="stop",
        )

    async def stream(self, request: GenerateRequest) -> AsyncIterator[GenerateChunk]:
        text = mock_text(request.prompt)
        for index in range(0, len(text), 24):
            yield GenerateChunk(text=text[index : index + 24], done=False)
        yield GenerateChunk(text="", done=True)

    async def tool_call(self, request: ToolCallRequest) -> ToolCallResponse:
        parsed = _explicit_call(request.prompt)
        if parsed is not None:
            name, arguments = parsed
            return ToolCallResponse(tool_name=name, arguments=arguments, text=None)
        generated = await self.generate(GenerateRequest(model=request.model, prompt=request.prompt))
        return ToolCallResponse(tool_name=None, arguments={}, text=generated.text)


def mock_text(prompt: str) -> str:
    """Build the mock provider's deterministic text."""

    stripped = prompt.lstrip()
    if stripped.lower().startswith("objective:"):
        return mock_decision(stripped)
    lowered = stripped.lower()
    if "html" in lowered or "website" in lowered:
        return (
            "<!doctype html><html><head><title>OMNE</title></head>"
            "<body><p>Generated by the mock provider.</p></body></html>"
        )
    compact = " ".join(stripped.split())
    return f"mock-response:{compact[:240]}"


def mock_decision(prompt: str) -> str:
    """Return one structured decision for an intelligence prompt. No tool runs."""

    objective = _objective_line(prompt)
    lowered = objective.lower()
    read = re.search(r"read(?:ing)? (?:the )?file (?P<path>\S+)", objective, re.IGNORECASE)
    launched = re.search(r"launch application (?P<name>.+)$", objective, re.IGNORECASE)
    tool_requests: list[dict[str, object]] = []
    if "os.system" in lowered or "unknown tool" in lowered:
        tool_requests.append({"name": "os.system", "arguments": {"command": "id"}})
    elif "scan wifi" in lowered:
        tool_requests.append({"name": "network.scan", "arguments": {}})
    elif launched is not None:
        tool_requests.append(
            {"name": "application.launch", "arguments": {"name": launched.group("name").strip()}}
        )
    elif "terminal.execute" in lowered:
        tool_requests.append(
            {"name": "terminal.execute", "arguments": {"argv": ["echo", "hello"], "cwd": "."}}
        )
    elif read is not None:
        tool_requests.append({"name": "filesystem.read", "arguments": {"path": read.group("path")}})
    clarification = "clarify" in lowered
    if clarification:
        final_response = "Which file should be read?"
    elif tool_requests:
        final_response = ""
    else:
        final_response = f"mock-response:{objective[:240]}"
    return json.dumps(
        {
            "intent": "act" if tool_requests else "conversation",
            "plan": ["use the tool gateway"] if tool_requests else ["respond"],
            "tool_requests": tool_requests,
            "expected_result": "a verified result",
            "clarification_required": clarification,
            "confirmation_required": "confirm before" in lowered,
            "final_response": final_response,
            "reasoning_summary": "Tools run only through the gateway.",
        }
    )


def _objective_line(prompt: str) -> str:
    first = prompt.splitlines()[0]
    _, _, value = first.partition(":")
    return value.strip()


def _explicit_call(prompt: str) -> tuple[str, dict[str, object]] | None:
    marker = "CALL "
    if marker not in prompt:
        return None
    body = prompt.split(marker, 1)[1].strip()
    name, _, raw_args = body.partition(" ")
    if not name:
        return None
    if not raw_args:
        return name, {}
    loaded = json.loads(raw_args)
    if not isinstance(loaded, dict):
        return name, {}
    return name, loaded
